In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split,cross_val_score,RandomizedSearchCV,GridSearchCV
from sklearn.preprocessing import StandardScaler

In [20]:
data = pd.read_csv(r"C:\Users\MALCOM_TREVOR\Desktop\DATA SCIENCE\MY PROJECT\ML\Classification Tasks\bank churn\data\churn_ABC Bank.csv",
                   skiprows = 1,index_col = "CustomerId")

## Data Understanding

In [22]:
data.shape

(10000, 13)

In [24]:
data.head()

,RowNumber,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
CustomerId,,,,,,,,,,,,,
15634602,1,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
15647311,2,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
15619304,3,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
15701354,4,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
15737888,5,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [27]:
data.tail()

,RowNumber,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
CustomerId,,,,,,,,,,,,,
15606229,9996,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
15569892,9997,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
15584532,9998,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
15682355,9999,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
15628319,10000,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [29]:
data.sample(n = 15)

,RowNumber,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
CustomerId,,,,,,,,,,,,,
15768945,8527,Chibueze,627,France,Male,27,1,62092.90,1,1,1,105887.04,0
15716284,2395,Ward,543,France,Male,43,9,0.00,2,1,1,78858.07,0
15723169,3785,Williams,640,France,Female,31,9,138857.59,1,1,0,48640.77,0
15599860,3784,Warner,647,Spain,Female,26,8,109958.15,1,1,1,136592.24,1
15579994,6422,Shaw,616,France,Male,23,8,73112.95,1,1,1,62733.05,0
15669501,6984,Kuo,706,France,Male,35,5,0.00,2,1,1,81718.37,0
15587535,748,Onyemauchechukwu,450,Spain,Female,46,5,177619.71,1,1,0,54227.06,0
15745624,5403,McKenzie,828,France,Male,37,4,0.00,2,1,0,94845.45,0
15583724,7460,Raymond,645,Spain,Female,29,4,0.00,2,1,1,74346.11,0
15586310,174,Ting,578,France,Male,30,4,169462.09,1,1,0,112187.11,0
15597945,22,Dellucci,636,Spain,Female,32,8,0.00,2,1,0,138555.46,0
15726796,3361,Brabyn,844,France,Male,38,7,111501.66,1,1,1,119333.38,0
15772250,5162,Udegbunam,842,Spain,Male,46,9,0.00,1,0,0,17268.02,0
15630913,1982,Rosas,476,Spain,Female,69,1,105303.73,1,0,1,134260.34,0
15653997,3802,Haynes,699,Spain,Male,31,6,114493.68,1,0,0,138396.32,0

In [65]:
data.columns

Index(['RowNumber', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age',
       'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='object')

In [67]:
data.dtypes

RowNumber            int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [69]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 15634602 to 15628319
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   Surname          10000 non-null  object
 2   CreditScore      10000 non-null  int64
 3   Geography        10000 non-null  object
 4   Gender           10000 non-null  object
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  float64
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
dtypes: float64(2), int64(8), object(3)
memory usage: 1.1+ MB

In [71]:
data[['CreditScore','Age','Tenure','NumOfProducts']].describe(include = 'int').T.style.background_gradient(cmap = 'summer')

In [72]:
data.isnull().sum()

RowNumber          0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [74]:
data.duplicated().sum()

0

## Data Cleaning and Preprocessing

In [81]:
data.drop(columns = ['RowNumber','Surname'])

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
CustomerId,,,,,,,,,,,
15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
15606229,771,France,Male,39,5,0.00,2,1,0,96270.64,0
15569892,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
15584532,709,France,Female,36,7,0.00,1,0,1,42085.58,1
15682355,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
15628319,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [84]:
data = data.drop(columns = ['RowNumber','Surname'])

In [104]:
data.rename(columns = {'CreditScore':'Credit Score','Geography':'Country lived','Tenure':'Time with us',
                       'NumOfProducts':'Property obtained through us','HasCrCard':"Has Credit Card",
                       "IsActiveMember":"Is Active Member",'EstimatedSalary':"Estimated Salary"})

,Credit_Score,Country_lived,Gender,Age,Time_with_us,Balance,Property_obtained_through_us,Has_Credit_Card,Is_Active_Member,Estimated Salary,Exited
CustomerId,,,,,,,,,,,
15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
15606229,771,France,Male,39,5,0.00,2,1,0,96270.64,0
15569892,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
15584532,709,France,Female,36,7,0.00,1,0,1,42085.58,1
15682355,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
15628319,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [115]:
data = data.rename(columns = {'CreditScore':'Credit Score','Geography':'Country lived','Tenure':'Time with us',
                       'NumOfProducts':'Property obtained through us','HasCrCard':"Has Credit Card",
                       "IsActiveMember":"Is Active Member",'EstimatedSalary':"Estimated Salary"})

In [117]:
data.columns.str.replace(" ","_")

Index(['Credit_Score', 'Country_lived', 'Gender', 'Age', 'Time_with_us',
       'Balance', 'Property_obtained_through_us', 'Has_Credit_Card',
       'Is_Active_Member', 'Estimated_Salary', 'Exited'],
      dtype='object')

In [119]:
data.columns = data.columns.str.replace(" ","_")

In [121]:
data

,Credit_Score,Country_lived,Gender,Age,Time_with_us,Balance,Property_obtained_through_us,Has_Credit_Card,Is_Active_Member,Estimated_Salary,Exited
CustomerId,,,,,,,,,,,
15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
15606229,771,France,Male,39,5,0.00,2,1,0,96270.64,0
15569892,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
15584532,709,France,Female,36,7,0.00,1,0,1,42085.58,1
15682355,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
15628319,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

## Exploratory Data Analysis

### *1. Customer Churn Analysis (Exited)*
- What percentage of customers have churned (Exited = 1)?
- Which features are most strongly correlated with customer churn?
- Do customers with higher credit scores churn less?
- Is there a relationship between tenure and churn rate?
- Does having a credit card or being an active member affect churn?

---

### *2. Demographic & Behavioral Analysis*
- How does age impact the likelihood of churn? Are older customers more likely to leave?
- Is there a gender-based difference in churn rates (e.g., do males or females churn more)?
- Does estimated salary influence customer retention?
- Are customers with higher balances more or less likely to churn?

---

### *3. Product & Engagement Analysis*
- Does the number of products a customer has influence churn?
- Are customers with longer tenures (longer relationship with the bank) less likely to churn?
- Is there a relationship between being an "active member" and churn?
- Do customers with credit cards behave differently from those without?

---

### *4. Credit & Financial Analysis*
- How does CreditScore relate to churn? Do lower credit scores predict higher churn?
- Is there a relationship between balance and credit score?
- Does salary play a role in credit card ownership or active membership?

---

### *5. Predictive Questions*
- Which machine learning model (e.g., logistic regression, random forest) best predicts churn?
- What are the most important features in predicting customer churn (feature importance)?

---

### *6. Business Strategy & Recommendations*
- Should the bank focus on retaining older customers or high-balance customers?
- Would offering more products reduce churn?
- Does increasing engagement (e.g., encouraging active membership) help retain customers?
- Should credit card incentives be adjusted based on salary or credit score?

- Perform *Exploratory Data Analysis (EDA)* (distributions, correlations, visualizations).
- Conduct *statistical tests* (t-tests, chi-square) to check for significant differences.
- Build a *predictive model* (classification) to predict churn.